### ISSUE TITLE
Een tab van de meest gebruikte sensoren? degene met de meeste kliks?

### ISSUE THREAD

**Issue by felixfalk2903** [vives-dust/frontend-old#17]

**Comment by sillevl** [comment]
hmm, misschien een leuk idee, maar ik twijfel over de meerwaarde. De meest populaire sensoren gaan promoten zal voor een nog grotere onderscheid gaan zorgen tussen de sensoren (hoewel er geen wedstrijd oid is). Populaire sensoren zullen alleen maar populairder worden, en niet populaire sensoren zullen meer naar de achtergrond geduwd worden... 

Maar om op het concept verder te gaan, zou het bvb geen idee zijn om de 5 dichtste sensoren weer te geven in een lijsten? Of eventueel een lijst van alle sensoren in je huidige gemeente/stad.

Dit zou nog aangevuld kunnen worden met een samengestelde analyse van die groep sensoren. bvb, gemiddelde van alle waarden samenvatten in 1 nieuwe virtuele waarde voor de gemeente/stad/ sensoren in de buurt.

Wat denken jullie?

**Comment by felixfalk2903** [comment]
De opmerking is inderdaad terecht,
Volgens mij zou jouw voorstel wel een meerwaarde kunnen betekenen voor het project en voor de gebruikers.
